services:
  - type: web
    name: portfolio
    runtime: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn portfolio.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: Portfolio_PostgreSQL_Databse
          property: connectionString
      - key: CLOUDINARY_URL
        sync: false
